package main

import (
	"fmt"
	"log"
	"net/url"
)

func main() {
	//encodedValue := "Hell%C3%B6+W%C3%B6rld%40Golang"
	//encodedValue := "----BEGIN%20CERTIFICATE%20REQUEST-----%0D%0AMIIBPDCB4QIBADB/MQswCQYDVQQGEwJDTjELMAkGA1UECAwCc2QxCzAJBgNVBAcM%0D%0AAndoMQ4wDAYDVQQKDAVmaXNlYzELMAkGA1UECwwCeWYxHTAbBgNVBAMMFDExMjIw%0D%0AMDAwMDA0MDAwMDAwMDA5MRowGAYJKoZIhvcNAQkBDAsxNjNAMTYzLmNvbTBZMBMG%0D%0AByqGSM49AgEGCCqBHM9VAYItA0IABENPvO9jZrevc6VTXcGLSdMOxO1vYWI2IlN+%0D%0AdZU/+87j8WDWztGcf99F78f04T5YHmQTp6dcGlf385U1ApWLIUqgADAMBggqgRzP%0D%0AVQGDdQUAA0gAMEUCIG0ERwFxaasQ9xUZG9cug4VxG0Mu5oJNmEywmINsXpbLAiEA%0D%0A3sTPaOlWb9pOxNrd8yX3DcmtkfNkvZBfQW4/rqyQzss=%0D%0A-----END%20CERTIFICATE%20REQUEST-----%0D%0A"
	encodedValue := "----BEGIN CERTIFICATE REQUEST-----\nMIIBPDCB4QIBADB/MQswCQYDVQQGEwJDTjELMAkGA1UECAwCc2QxCzAJBgNVBAcM\nAndoMQ4wDAYDVQQKDAVmaXNlYzELMAkGA1UECwwCeWYxHTAbBgNVBAMMFDExMjIw\nMDAwMDA0MDAwMDAwMDA5MRowGAYJKoZIhvcNAQkBDAsxNjNAMTYzLmNvbTBZMBMG\nByqGSM49AgEGCCqBHM9VAYItA0IABENPvO9jZrevc6VTXcGLSdMOxO1vYWI2IlN \ndZU/ 87j8WDWztGcf99F78f04T5YHmQTp6dcGlf385U1ApWLIUqgADAMBggqgRzP\nVQGDdQUAA0gAMEUCIG0ERwFxaasQ9xUZG9cug4VxG0Mu5oJNmEywmINsXpbLAiEA\n3sTPaOlWb9pOxNrd8yX3DcmtkfNkvZBfQW4/rqyQzss=\n-----END CERTIFICATE REQUEST-----\n"
	decodedValue, err := url.QueryUnescape(encodedValue)
	if err != nil {
		log.Fatal(err)
		return
	}
	fmt.Println(decodedValue)
}
